# Generated by Django 4.1.3 on 2023-05-09 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="fProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("phone_number", models.CharField(max_length=10, null=True)),
                ("location", models.CharField(max_length=15, null=True)),
                ("country", models.CharField(max_length=15, null=True)),
                ("estb_Year", models.IntegerField(max_length=4)),
                ("small_description", models.CharField(max_length=50)),
                ("large_description", models.CharField(max_length=200)),
                ("min_investment", models.IntegerField()),
                ("no_of_branches", models.IntegerField()),
                (
                    "image",
                    models.ImageField(blank="true", null=True, upload_to="franchisor"),
                ),
            ],
        ),
    ]
