# Generated by Django 4.1.3 on 2023-05-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchisor", "0002_alter_fprofile_estb_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fprofile",
            name="country",
        ),
        migrations.RemoveField(
            model_name="fprofile",
            name="estb_Year",
        ),
        migrations.RemoveField(
            model_name="fprofile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="fprofile",
            name="large_description",
        ),
        migrations.RemoveField(
            model_name="fprofile",
            name="location",
        ),
        migrations.RemoveField(
            model_name="fprofile",
            name="min_investment",
        ),
        migrations.RemoveField(
            model_name="fprofile",
            name="no_of_branches",
        ),
        migrations.RemoveField(
            model_name="fprofile",
            name="small_description",
        ),
        migrations.AddField(
            model_name="fprofile",
            name="about_us",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="fprofile",
            name="anticipated_return_on_investment",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fprofile",
            name="brand_fee",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fprofile",
            name="floor_area_required",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fprofile",
            name="investment",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fprofile",
            name="likely_payback_period",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fprofile",
            name="mission",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="fprofile",
            name="royalty",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="fprofile",
            name="vision",
            field=models.TextField(null=True),
        ),
    ]
