# Generated by Django 4.1.3 on 2023-05-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("franchisor", "0004_fprofile_franchise_commenced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fprofile",
            name="category",
            field=models.CharField(
                choices=[
                    ("Automotive", "Automotive"),
                    ("Beauty&Health", "Beauty&Health"),
                    ("Dealers & Distributers", "Dealers & Distributers"),
                    ("Education", "Education"),
                    ("Fashion", "Fashion"),
                    ("Food and Beverage", "Food and Beverage"),
                    ("Home Based Business", "Home Based Business"),
                    ("Hotel Travel & Tourism", "Hotel Travel & Tourism"),
                    ("Retail", "Retail"),
                    ("Sports,Fitness& Entertainment", "Sports,Fitness& Entertainment"),
                ],
                max_length=1000,
                null=True,
            ),
        ),
    ]
